"""The S3 v2 archive reader, against a miniature archive with the real layout.

The real archive is 5.2 GB and is not in this repo. Its *layout* is cheap to reproduce exactly
— ``S3_v2/imgs/{split}/{stem}/{stem}_rDDD.jpg`` plus ``S3_v2/masks/{split}/{stem}.png`` — so
the reading path is tested on a synthetic archive built to that shape, with frames generated by
a forward model whose geometry is known. That covers everything except the pixel values in the
real file, and it covers the failure that actually happened: a section whose mask and frames
disagree on shape crashed the first run against real data.
"""

from __future__ import annotations

import importlib.util
import io
import sys
import zipfile
from pathlib import Path
from types import ModuleType

import numpy as np
import pytest
from PIL import Image

from reefprint.acquire.phantom import StageRotation, crossed_polars_stage_series
from reefprint.polarim.geometry import HarmonicSignature, HarmonicVerdict, harmonic_signature


def _load_experiment() -> ModuleType:
    """Import ``experiments/002-s3v2-geometry/run.py`` by path.

    Experiment directories are numbered so the sequence is legible on disk, which makes them
    illegal package names. Loading by path keeps the numbering and still lets the reader be
    tested — the alternative, an un-numbered importable copy, is the sort of duplicate that
    drifts from the script that is actually run.
    """
    path = Path(__file__).resolve().parents[1] / "experiments" / "002-s3v2-geometry" / "run.py"
    spec = importlib.util.spec_from_file_location("s3v2_geometry_experiment", path)
    if spec is None or spec.loader is None:  # pragma: no cover - would mean the file vanished
        pytest.fail(f"cannot load the experiment script at {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


_experiment = _load_experiment()
list_sections = _experiment.list_sections
read_section = _experiment.read_section
section_frames = _experiment.section_frames

SHAPE = (64, 96)


def _write_archive(path, *, stems=("S3_train_01",), frame_shape=None, n_angles=72) -> StageRotation:
    """Build a miniature S3 v2 archive. ``frame_shape`` overrides to force a mismatch."""
    stage = crossed_polars_stage_series(n_angles=n_angles, shape=SHAPE, seed=2)
    frames = stage.series.frames
    # Clip, never cast: a raw uint8 cast wraps negatives. See tests/test_geometry.py.
    scaled = np.clip(np.round(frames / max(frames.max(), 1e-9) * 255.0), 0.0, 255.0)

    with zipfile.ZipFile(path, "w") as archive:
        for stem in stems:
            mask = (stage.labels + 1).astype(np.uint8)
            buffer = io.BytesIO()
            Image.fromarray(mask).save(buffer, format="PNG")
            archive.writestr(f"S3_v2/masks/train/{stem}.png", buffer.getvalue())

            for index, degrees in enumerate(range(0, 360, 360 // n_angles)):
                frame = scaled[index].astype(np.uint8)
                if frame_shape is not None:
                    frame = np.zeros(frame_shape, dtype=np.uint8)
                buffer = io.BytesIO()
                Image.fromarray(frame).save(buffer, format="JPEG", quality=95)
                archive.writestr(
                    f"S3_v2/imgs/train/{stem}/{stem}_r{degrees:03d}.jpg", buffer.getvalue()
                )
    return stage


def test_the_reader_finds_sections_and_their_rotation_frames(tmp_path) -> None:
    archive_path = tmp_path / "S3_v2.zip"
    _write_archive(archive_path)

    with zipfile.ZipFile(archive_path) as archive:
        names = archive.namelist()

    assert list_sections(names) == [("train", "S3_train_01")]
    frames = section_frames(names, "train", "S3_train_01")
    assert len(frames) == 72
    assert [d for d, _ in frames][:4] == [0, 5, 10, 15]


def test_a_stage_rotation_archive_is_read_back_as_a_stage_rotation(tmp_path) -> None:
    """End to end: build the archive, read it, and recover the geometry it was built with.

    JPEG is lossy and the frames are quantised to 8 bits, so this also demonstrates that the
    verdict survives the compression the real archive applies.
    """
    archive_path = tmp_path / "S3_v2.zip"
    _write_archive(archive_path)
    rng = np.random.default_rng(0)

    with zipfile.ZipFile(archive_path) as archive:
        names = archive.namelist()
        data = read_section(archive, names, "train", "S3_train_01", rng, n_samples=1500)

    assert "skipped" not in data
    signature = harmonic_signature(data["intensities"], data["angles_rad"])
    assert signature.verdict is HarmonicVerdict.FOURTH


def test_a_mask_frame_shape_mismatch_is_reported_not_raised(tmp_path) -> None:
    """The failure that killed the first real run, as a skip with both shapes named.

    Dying on the first mismatched section hides how many are mismatched, which is the number
    that decides whether it is one bad section or a transposed dataset.
    """
    archive_path = tmp_path / "S3_v2.zip"
    _write_archive(archive_path, frame_shape=(SHAPE[1], SHAPE[0]))
    rng = np.random.default_rng(0)

    with zipfile.ZipFile(archive_path) as archive:
        names = archive.namelist()
        data = read_section(archive, names, "train", "S3_train_01", rng, n_samples=500)

    assert data["skipped"] == "mask/frame shape mismatch"
    assert data["mask_shape"] == [64, 96]
    assert data["frame_shape"] == [96, 64]


def test_a_section_with_too_few_frames_is_skipped_rather_than_inverted(tmp_path) -> None:
    archive_path = tmp_path / "S3_v2.zip"
    _write_archive(archive_path, n_angles=4)
    rng = np.random.default_rng(0)

    with zipfile.ZipFile(archive_path) as archive:
        names = archive.namelist()
        data = read_section(archive, names, "train", "S3_train_01", rng, n_samples=500)

    assert "only 4 rotation frames" in data["skipped"]


def _flat_signature(*, dc: np.ndarray, snr_2: np.ndarray) -> HarmonicSignature:
    """A hand-built ``HarmonicSignature`` with a chosen per-pixel brightness and 2nd-harmonic
    SNR, and no 4th-harmonic content at all — for testing ``pool_signatures`` selection logic
    in isolation from the fit itself."""
    n = dc.size
    return HarmonicSignature(
        amplitude_2=snr_2.copy(),
        amplitude_4=np.zeros(n),
        floor_2=np.ones(n),
        floor_4=np.ones(n),
        dc=dc,
        n_angles=72,
        verdict=HarmonicVerdict.NEITHER,
        snr_2=0.0,
        snr_4=0.0,
        detection_snr=5.0,
    )


def test_pool_signatures_can_restrict_to_the_brightest_pixels() -> None:
    """N3's ``NEITHER`` verdict leans on the physics claim that analyser modulation grows as
    ``2/a`` relative to stage modulation as brightness (S0) rises. ``brightness_quantile``
    lets that claim be checked directly: restrict pooling to the brightest grains — the ones
    where the analyser signal, if present, would be least buried — before taking the median.

    Built so the two halves disagree: the dim pixels sit at snr_2 = 2 (below
    ``DETECTION_SNR``), the bright half at snr_2 = 6 (above it). Pooling everything gives a
    median of 4 and stays ``NEITHER``; restricting to the top half by ``dc`` isolates the
    bright group and the verdict flips to ``SECOND``. ``modulating_fraction=1.0`` disables the
    unrelated modulation-strength selection so only the brightness restriction is on trial.
    """
    pool_signatures = _experiment.pool_signatures
    dc = np.arange(1, 21, dtype=float)
    snr_2 = np.where(dc <= 10, 2.0, 6.0)
    signature = _flat_signature(dc=dc, snr_2=snr_2)

    snr_2_all, _, verdict_all, n_all, _ = pool_signatures([signature], modulating_fraction=1.0)
    assert verdict_all is HarmonicVerdict.NEITHER
    assert snr_2_all == pytest.approx(4.0)
    assert n_all == 20

    snr_2_bright, _, verdict_bright, n_bright, _ = pool_signatures(
        [signature], modulating_fraction=1.0, brightness_quantile=0.5
    )
    assert verdict_bright is HarmonicVerdict.SECOND
    assert snr_2_bright == pytest.approx(6.0)
    assert n_bright == 10


@pytest.mark.placeholder
def test_the_real_s3_v2_archive_has_been_measured() -> None:
    """N3 is not closed until this runs on the real 5.2 GB archive.

    Everything above tests the reader against a synthetic archive of the correct shape. That
    proves the code, not the dataset. The verdict on the actual LumenStone S3 v2 frames decides
    whether week-1 leg (b) can use the Stokes inversion at all, and it is a one-command answer:

        uv run python experiments/002-s3v2-geometry/run.py --archive <path>/S3_v2.zip

    The archive lives on Sibusiso's machine (5227.2 MB, downloaded 2026-08-20). Delete this
    test and record the result in docs/BUILDLOG.md once it has been run.
    """
    pytest.fail("NOT MEASURED — N3 open: run experiments/002-s3v2-geometry/run.py on S3_v2.zip")
