import {useEffect,useState} from 'react';
import {CheckCircle2,Microscope,Clock3} from 'lucide-react';
export type LiveEvidence={revision:number;preview_url:string|null;preview_size:number[];analysed_pixels:number;image_pixels:number;coverage_fraction:number;phases:{name:string;color:string;pixels:number;area_pct:number}[];last_tile_confidence:number;completed_boxes:number[][];provisional:boolean;basis:string;aggregation?:string};
export type AnalysisState={stage?:string;completed?:number;total?:number;box?:number[];image_size?:number[];evidence?:LiveEvidence};
const stages=['preparing','segmenting','measuring','saving'];
const names=['Load image','Classify pixels','Measure grains','Save result'];
export default function AnalysisProgress({progress,status,startedAt,mode}:{progress?:AnalysisState;status?:string;startedAt:number;mode:string}){
 const [seconds,setSeconds]=useState(0);
 useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.floor((Date.now()-startedAt)/1000)));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[startedAt]);
 const stage=progress?.stage||'queued',index=stages.indexOf(stage),evidence=progress?.evidence;
 return <section className="analysis-telemetry" aria-label="Live pixel analysis"><div className="telemetry-heading"><Microscope size={18}/><strong>{stage==='queued'?'Analysis queued':index<0?'Starting analysis':names[index]}</strong><span><Clock3 size={14}/>{seconds}s</span></div><ol className="analysis-steps">{stages.map((s,i)=><li key={s} className={i<index?'done':i===index?'current':''}>{i<index?<CheckCircle2 size={14}/>:<span className="stage-dot"/>}{names[i]}</li>)}</ol><div className="telemetry-counts" role="status" aria-live="polite"><span>{progress?.total?`${progress.completed||0} of ${progress.total} ${mode==='full'?'tiles':'fields'} completed`:'Waiting for the first prediction'}</span>{!!evidence?.analysed_pixels&&<span>{evidence.analysed_pixels.toLocaleString()} pixels · {(evidence.coverage_fraction*100).toFixed(1)}% of image</span>}</div>{stage==='segmenting'&&!!progress?.total&&<progress aria-label="Classified fields or tiles" max={progress.total} value={progress.completed||0}/>}{evidence?.provisional&&<div className="provisional-box"><strong>Provisional · {progress?.completed} of {progress?.total} fields</strong>{evidence.phases.map(p=><div className="phase-row" key={p.name}><span>{p.name==='background'?'Background / resin':p.name}</span><div className="track"><b style={{width:p.area_pct+'%',background:p.color}}/></div><em>{p.area_pct.toFixed(1)}%</em></div>)}</div>}<p>{evidence?.analysed_pixels?`Coloured pixels are preliminary predictions from completed ${mode==='full'?'tiles':'fields'}. Clear areas have not been analysed. ${mode==='full'?'Overlapping predictions are blended when the job finishes.':'Fractions may change until the job finishes.'}`:'The image stays visible while the model loads. Predictions appear when the first field finishes.'}</p></section>;
}