import {useEffect,useRef,useState,lazy,Suspense} from 'react';
import {Layers,Microscope,Search,Upload,Play,ArrowRight,ChevronRight,ChevronDown,FileText,Box,CheckCircle2,AlertCircle,ZoomIn,ZoomOut,Maximize2,RotateCcw,Download,SlidersHorizontal,MapPin,Beaker,Activity,Database,FlaskConical,Info,Loader2,PanelLeftClose,X,Check,Image as ImageIcon} from 'lucide-react';
const Spatial=lazy(()=>import('./Spatial'));
type Sample={id:string;thumbnail_url:string;dimensions:number[];dataset:string;has_prediction:boolean};
type Phase={name:string;area_pct:number;color:string};
type Result={id:string;result_id:string|null;prediction_source:string;phases:Phase[];confidence:number|null;advisory:{action:string;reason:string};model_sha:string;elapsed_seconds:number|null;raw_url:string;overlay_url:string|null;mask_url:string|null;verified:boolean;scope?:string;association_index?:number|null};
type Report={model_sha:string;checkpoint_available:boolean;checkpoint_matches_report:boolean;report_source:string;metrics:{mean_iou:number;pixel_accuracy:number;n_test_images:number;classes:{name:string;iou:number;recall?:number;color:string}[]}|null;limitations:string[];download_url:string};
type Job={id:string;status:string;result?:Result;error?:string};
const palette:Record<string,string>={chalcopyrite:'#f28136',pyrrhotite:'#119eae',pentlandite:'#9562d1',magnetite:'#d6ac25',background:'#8c96a1'};
const title=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
async function api<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch('/api'+path,options);if(!r.ok){let e:any;try{e=await r.json()}catch{e={detail:r.statusText}}throw Error(e.detail||'Request failed')}return r.json()}
const post=(body:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function saved(id:string){try{return JSON.parse(localStorage.getItem('reefprint-record-'+id)||'{}')}catch{return {}}}
export default function App(){
 const[page,setPage]=useState('Workspace'),[samples,setSamples]=useState<Sample[]>([]),[selected,setSelected]=useState('test_11'),[result,setResult]=useState<Result|null>(null),[report,setReport]=useState<Report|null>(null),[health,setHealth]=useState<any>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[layer,setLayer]=useState('raw'),[opacity,setOpacity]=useState(60),[zoom,setZoom]=useState(1),[busy,setBusy]=useState(false),[job,setJob]=useState<Job|null>(null),[record,setRecord]=useState<any>({}),[recordOpen,setRecordOpen]=useState(false),[recordSaved,setRecordSaved]=useState(false),[sim,setSim]=useState<any>(null),[simBusy,setSimBusy]=useState(false),[loading,setLoading]=useState(true),[mode,setMode]=useState('field'),[mobileLibrary,setMobileLibrary]=useState(false);
 const uploadRef=useRef<HTMLInputElement>(null),assayRef=useRef<HTMLInputElement>(null),viewer=useRef<HTMLDivElement>(null);
 const active=samples.find(s=>s.id===selected);
 useEffect(()=>{Promise.all([api<Sample[]>('/samples'),api<Report>('/report'),api<any>('/health')]).then(([s,r,h])=>{setSamples(s);setReport(r);setHealth(h);if(s.length&&!s.find(x=>x.id===selected))setSelected(s[0].id)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{let cancelled=false;setResult(null);setLayer('raw');setZoom(1);setSim(null);setRecord(saved(selected));setRecordSaved(false);api<Result>('/samples/'+selected).then(r=>{if(!cancelled){setResult(r);if(r.mask_url)setLayer('overlay')}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[selected]);
 useEffect(()=>{if(!job||['complete','failed'].includes(job.status))return;const timer=setInterval(()=>{api<Job>('/jobs/'+job.id).then(j=>{setJob(j);if(j.status==='complete'&&j.result){setResult(j.result);setLayer('overlay');setBusy(false);setSamples(s=>s.map(x=>x.id===j.result!.id?{...x,has_prediction:true}:x))}if(j.status==='failed'){setError(j.error||'Analysis failed. Try another sample.');setBusy(false)}}).catch(e=>{setBusy(false);setError(e.message);setJob(null)})},1200);return()=>clearInterval(timer)},[job?.id,job?.status]);
 async function analyse(){setBusy(true);setError('');setSim(null);setLayer('raw');setResult(r=>r?{...r,result_id:null,phases:[],confidence:null,mask_url:null,overlay_url:null,raw_url:'/api/samples/'+selected+'/image?layer=original',scope:'Native image · analysis in progress'}:r);try{setJob(await api<Job>('/inferences',post({sample_id:selected,mode})))}catch(e:any){setBusy(false);setError(e.message)}}
 async function upload(file?:File){if(!file)return;setError('');try{const data=new FormData();data.append('file',file);const s=await api<Sample>('/upload',{method:'POST',body:data});setSamples(prev=>[s,...prev]);setSelected(s.id);setPage('Workspace')}catch(e:any){setError(e.message)}}
 async function simulate(){if(!result?.result_id)return;setSimBusy(true);setError('');try{setSim(await api('/simulate',post({result_id:result.result_id})))}catch(e:any){setError(e.message)}finally{setSimBusy(false)}}
 function saveRecord(){try{localStorage.setItem('reefprint-record-'+selected,JSON.stringify(record));setRecordSaved(true)}catch{setError('Browser storage is full. Export the record before clearing space.')}}
 async function assay(file?:File){if(!file)return;try{const lines=(await file.text()).trim().split(/\r?\n/);const rows=lines.slice(1).map(l=>l.split(',')).map(([element,value,unit])=>({element:element?.trim(),value:Number(value),unit:unit?.trim()}));if(!rows.length||rows.some(r=>!r.element||!Number.isFinite(r.value)||!r.unit))throw Error('CSV needs a header and element,value,unit rows.');const next={...record,assays:rows,assayFile:file.name};setRecord(next);localStorage.setItem('reefprint-record-'+selected,JSON.stringify(next))}catch(e:any){setError(e.message)}}
 const phases=result?.phases?.filter(p=>p.name!=='background')||[],hasResult=!!result?.result_id;
 const filtered=samples.filter(s=>s.id.toLowerCase().includes(query.toLowerCase()));
 const metrics=report?.metrics;
 function navigate(p:string){setPage(p);setMobileLibrary(false)}
 const runButton=<button className="button primary" onClick={analyse} disabled={busy||!health?.checkpoint_available||!active}>{busy?<Loader2 className="spin"/>:<Play size={15}/>} {busy?'Analysing sample…':'Run analysis'}</button>;
 const evidence=<section className="panel evidence-panel"><div className="section-head"><div className="heading-icon"><CheckCircle2/><div><h2>Validation evidence</h2><p>Recorded test results · checkpoint-bound</p></div></div><button className="text-button" onClick={()=>navigate('Reports')}>Full report <ArrowRight size={16}/></button></div>{metrics?<div className="evidence-body"><div className="metric"><strong>{metrics.mean_iou.toFixed(3)}</strong><span>Mean IoU</span><small>Includes background</small></div><div className="metric"><strong>{(metrics.pixel_accuracy*100).toFixed(1)}<em>%</em></strong><span>Pixel accuracy</span><small>{metrics.n_test_images} held-out sections</small></div><div className="mini-bars">{metrics.classes.filter(c=>c.name!=='background').map(c=><div className="mini-row" key={c.name}><span><i style={{background:palette[c.name]||c.color}}/>{title(c.name)}</span><div className="track"><b style={{width:c.iou*100+'%',background:palette[c.name]||c.color}}/></div><strong>{c.iou.toFixed(3)}</strong></div>)}</div><div className="evidence-note"><Info size={17}/><p>Magnetite is missed in this checkpoint. A zero score remains visible; area estimates are image fractions, not ore grade.</p></div></div>:<p className="empty-inline">No report matched to the active checkpoint. Scores will appear only with their provenance.</p>}</section>;
 const workflow=<section className="panel process-panel"><div className="section-head"><div className="heading-icon"><SlidersHorizontal/><div><h2>From prediction to process decision</h2><p>Inspect the evidence, then test a change in the local simulator.</p></div></div><span className="badge amber">Simulator only</span></div><div className="process-flow"><div className="flow-cell"><div className="step-title"><span>1</span><h3>Model output</h3></div><strong>{hasResult?title(selected):'Choose and analyse a sample'}</strong><p>{hasResult?'Phase map and apparent 2D association from the selected image.':'The model will generate a phase map from a reflected-light micrograph.'}</p><span className="small-status">{hasResult?result?.scope||'512 × 512 field':'Awaiting analysis'}</span></div><ArrowRight className="flow-arrow"/><div className="flow-cell"><div className="step-title"><span>2</span><h3>Review advisory</h3></div><strong>{hasResult?result?.advisory.action:'No recommendation yet'}</strong><p>{hasResult?result?.advisory.reason:'Advice appears after inference. No plant action is triggered by uploading an image.'}</p></div><ArrowRight className="flow-arrow"/><div className="flow-cell"><div className="step-title"><span>3</span><h3>Test the setpoint</h3></div><div className="setpoint"><span>Regrind enabled</span><strong>{sim?String(sim.before)+' → '+String(sim.after):'—'}</strong></div><button className="button" disabled={!hasResult||simBusy||busy} onClick={simulate}>{simBusy?<Loader2 className="spin"/>:<FlaskConical size={16}/>}Test in simulator</button><p>{sim?sim.reason:'Explicit action. Unverified samples and low-confidence results are held.'}</p>{sim&&<span className={'badge '+(sim.state==='applied'?'green':'amber')}>{sim.state}</span>}</div></div></section>;
 return <><a className="skip-link" href="#main">Skip to workspace</a><header className="masthead"><a className="brand" href="#workspace" onClick={()=>navigate('Workspace')}><svg width="35" height="37" viewBox="0 0 40 42" aria-hidden="true"><path d="m3 13 17-10 17 10-17 9zM3 22l17 9 17-9v8L20 40 3 30z" fill="currentColor"/></svg><span>REEFPRINT <small>KHANYA · Mineral intelligence</small></span></a><nav aria-label="Main navigation">{[{name:'Workspace',icon:Microscope},{name:'Samples',icon:Database},{name:'Spatial',icon:Box},{name:'Reports',icon:FileText}].map(({name,icon:Icon})=><button key={name} className={page===name?'active':''} aria-current={page===name?'page':undefined} onClick={()=>navigate(name)}><Icon size={16}/>{name}</button>)}</nav><div className="connection"><span className={health?'dot connected':'dot'}/><span>{health?'Local model service':'Connecting…'}<small>Research workspace</small></span></div></header>
 <main id="main"><div className="workspace-heading"><div><div className="breadcrumb"><Layers size={14}/> LumenStone S2 <ChevronRight size={13}/> {page}</div><h1>{page==='Workspace'?'From specimen to insight':page==='Samples'?'Your sample library':page==='Spatial'?'Specimens in spatial context':'Evidence you can inspect'}</h1><p>{page==='Workspace'?'Explore mineral phases, understand the evidence, test the next decision.':page==='Samples'?'One record connects the image, observations and analysis.':page==='Spatial'?'Inspect image planes in 3D. Add surveyed locations before making geological claims.':'Recorded evaluation, model identity and the limits behind every result.'}</p></div><button className="button" disabled={busy} onClick={()=>uploadRef.current?.click()}><Upload size={16}/>Add micrograph</button><input ref={uploadRef} hidden type="file" accept="image/png,image/jpeg,image/tiff" onChange={e=>upload(e.target.files?.[0])}/></div>
 {error&&<div role="alert" className="error-banner"><AlertCircle size={18}/><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}
 {loading&&<div className="loading-strip" role="status"><Loader2 className="spin" size={16}/>Loading sample library and model evidence…</div>}
 {page==='Workspace'&&<><button className="mobile-library button" onClick={()=>setMobileLibrary(!mobileLibrary)}><Database size={16}/>Select sample <ChevronDown size={16}/></button><div className="workbench-grid"><aside className={'panel sample-library '+(mobileLibrary?'mobile-open':'')}><div className="section-head"><div><h2>Sample library <span className="count">{samples.length}</span></h2><p>Polished sections · S2 dataset</p></div></div><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a sample…" aria-label="Search samples"/></label><div className="sample-list">{filtered.map(s=><button key={s.id} className={'sample-item '+(selected===s.id?'selected':'')} disabled={busy} onClick={()=>{setSelected(s.id);setMobileLibrary(false)}}><img src={s.thumbnail_url} alt="" loading="lazy"/><span><strong>{title(s.id)}</strong><small>{s.dimensions.join(' × ')} px</small><span className="sample-state">{s.has_prediction?'Analysis available':'Held-out section'}</span></span><ChevronRight size={14}/></button>)}{!filtered.length&&<p className="empty-inline">No samples match your search.</p>}</div><div className="library-footer"><Database size={15}/><span>Original micrographs<br/><small>No synthetic mineral imagery</small></span></div></aside>
 <section className="panel image-panel"><div className="section-head"><div><h2>{title(selected)} <span className="badge neutral">S2 micrograph</span></h2><p>{hasResult?result?.scope:'Native image · reflected-light microscopy'}</p></div><div className="run-tools"><select aria-label="Inference scope" value={mode} onChange={e=>setMode(e.target.value)} disabled={busy}><option value="field">Live field</option><option value="full">Full section</option></select>{runButton}</div></div><div className="viewer-toolbar"><div className="segmented" aria-label="Image layer">{['raw','overlay','mask'].map(l=><button key={l} aria-pressed={layer===l} disabled={l!=='raw'&&!hasResult} className={layer===l?'selected':''} onClick={()=>setLayer(l)}>{l==='raw'?'Original':l==='overlay'?'Phase overlay':'Phase mask'}</button>)}</div><button className="icon-button" title="Open image fullscreen" aria-label="Open image fullscreen" onClick={()=>viewer.current?.requestFullscreen?.()}><Maximize2 size={16}/></button></div>
 <div className="image-stage" ref={viewer}><div className="image-transform" style={{transform:'scale('+zoom+')'}}>{result?.raw_url&&<img className="specimen-image" src={result.raw_url} alt={'Reflected-light micrograph '+selected}/>} {hasResult&&layer!=='raw'&&<img className="mask-image" src={result?.mask_url||undefined} style={{opacity:layer==='mask'?1:opacity/100}} alt="Model-predicted mineral phase segmentation"/>}</div><div className="image-caption"><span>{layer==='raw'?'Original acquisition':layer==='overlay'?'Prediction over original':'Model prediction'}</span><span>{hasResult?result?.prediction_source==='fresh'?'Fresh inference':'Saved inference':'Ready for analysis'}</span></div>{busy&&<div className="inference-progress" role="status"><Loader2 className="spin"/><div><strong>Identifying mineral phases</strong><small>{mode==='full'?'Full-resolution tiling can take several minutes.':'Running the actual checkpoint on a 512 px field.'}</small></div></div>}</div>
 <div className="viewer-footer"><div className="zoom-tools"><button className="icon-button" aria-label="Zoom out" disabled={zoom<=1} onClick={()=>setZoom(Math.max(1,zoom-.25))}><ZoomOut size={17}/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom in" disabled={zoom>=3} onClick={()=>setZoom(Math.min(3,zoom+.25))}><ZoomIn size={17}/></button><button className="icon-button" aria-label="Reset view" onClick={()=>setZoom(1)}><RotateCcw size={15}/></button></div><label className="opacity">Overlay <input aria-label="Overlay opacity" type="range" min="0" max="100" value={opacity} disabled={layer!=='overlay'} onChange={e=>setOpacity(Number(e.target.value))}/><span>{opacity}%</span></label></div><div className="legend">{Object.entries(palette).filter(([n])=>n!=='background').map(([n,c])=><span key={n}><i style={{background:c}}/>{title(n)}</span>)}</div></section>
 <aside className="panel phase-panel"><div className="section-head"><div><h2>Phase composition</h2><p>Predicted image-area fraction</p></div><Microscope size={19}/></div>{hasResult?<><div className="composition-stack">{result?.phases.map(p=><div title={title(p.name)+' '+p.area_pct.toFixed(1)+'%'} key={p.name} style={{width:p.area_pct+'%',background:palette[p.name]||p.color}}/>)}</div><div className="phase-bars">{phases.map(p=><div className="phase-row" key={p.name}><div><span><i style={{background:palette[p.name]||p.color}}/>{title(p.name)}</span><strong>{p.area_pct.toFixed(1)}<small>%</small></strong></div><div className="track"><b style={{width:p.area_pct+'%',background:palette[p.name]||p.color}}/></div></div>)}</div><div className="background-row">Background / other <strong>{(result?.phases.find(p=>p.name==='background')?.area_pct||0).toFixed(1)}%</strong></div><div className="confidence-box"><span>Mean model confidence <Info size={13}/></span><strong>{((result?.confidence||0)*100).toFixed(1)}%</strong><small>Uncalibrated model score; not probability of a correct result.</small></div></>:<div className="phase-empty"><Microscope size={32}/><h3>Your phase map starts here</h3><p>Run analysis on the selected micrograph to see composition and the model's recommendation.</p>{runButton}</div>}<div className="provenance"><h3>Analysis provenance</h3><dl><dt>Model</dt><dd>S2 patch segmenter</dd><dt>Checkpoint</dt><dd title={report?.model_sha}>{report?.model_sha?.slice(0,12)||'Checking…'}</dd><dt>Source</dt><dd>{hasResult?result?.prediction_source:'Awaiting analysis'}</dd><dt>Runtime</dt><dd>{result?.elapsed_seconds!=null?result.elapsed_seconds.toFixed(1)+' s':'Not measured yet'}</dd></dl><button className="text-button" disabled={!hasResult} onClick={()=>download(result,selected+'-inference.json')}>Download analysis <Download size={14}/></button></div></aside></div>
 <div className="context-row">{evidence}<section className="panel assay-panel"><div className="section-head"><div className="heading-icon"><Beaker/><div><h2>Elemental context</h2><p>XRF or laboratory assay</p></div></div></div>{record.assays?.length?<table className="assay-table"><thead><tr><th>Element</th><th>Value</th><th>Unit</th></tr></thead><tbody>{record.assays.map((a:any,i:number)=><tr key={i}><td>{a.element}</td><td>{a.value}</td><td>{a.unit}</td></tr>)}</tbody></table>:<p className="empty-inline">No assay attached. Import a CSV for this specimen to compare elemental chemistry with the phase map.</p>}<button className="text-button" onClick={()=>assayRef.current?.click()}><Upload size={14}/>Import assay CSV</button><input hidden ref={assayRef} type="file" accept=".csv" onChange={e=>assay(e.target.files?.[0])}/><small className="assay-note">element,value,unit · Stored in this browser. XRF measures elements, not mineral phases.</small></section></div>{workflow}
 <section className="panel record-panel"><button className="record-toggle" aria-expanded={recordOpen} onClick={()=>setRecordOpen(!recordOpen)}><span><MapPin size={17}/>Sample record & field notes</span><ChevronDown size={17}/></button>{recordOpen&&<div className="record-body"><p>Optional metadata. Saved on this device; cloud sync is not connected.</p><div className="record-fields">{[['sample_label','Sample label'],['latitude','Latitude'],['longitude','Longitude'],['depth','Depth (m)']].map(([key,label])=><label key={key}>{label}<input type={key==='sample_label'?'text':'number'} step="any" value={record[key]||''} onChange={e=>{setRecord({...record,[key]:e.target.value});setRecordSaved(false)}}/></label>)}</div><label>Field notes<textarea value={record.notes||''} onChange={e=>{setRecord({...record,notes:e.target.value});setRecordSaved(false)}} placeholder="Acquisition conditions, sample preparation, observations…"/></label><div className="record-actions"><button className="button primary" onClick={saveRecord}>{recordSaved?<Check size={16}/>:null}{recordSaved?'Saved on this device':'Save sample record'}</button><button className="button" onClick={()=>download({...record,sample_id:selected},selected+'-record.json')}>Export record</button></div></div>}</section></>}
 {page==='Samples'&&<section className="panel full-panel"><div className="section-head"><div><h2>All specimens</h2><p>{samples.length} images · select a row to open its workspace</p></div><label className="search"><Search size={16}/><input placeholder="Search sample ID" aria-label="Search sample ID" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-scroll"><table className="sample-table"><thead><tr><th>Specimen</th><th>Dataset</th><th>Dimensions</th><th>Analysis</th><th/></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><button className="sample-link" disabled={busy} onClick={()=>{setSelected(s.id);navigate('Workspace')}}><img src={s.thumbnail_url} alt=""/><strong>{title(s.id)}</strong></button></td><td>{s.dataset}</td><td>{s.dimensions.join(' × ')} px</td><td><span className={'badge '+(s.has_prediction?'green':'neutral')}>{s.has_prediction?'Available':'Ready to analyse'}</span></td><td><button className="icon-button" aria-label={'Open '+s.id} disabled={busy} onClick={()=>{setSelected(s.id);navigate('Workspace')}}><ArrowRight size={17}/></button></td></tr>)}</tbody></table></div></section>}
 {page==='Spatial'&&<section className="panel spatial-panel"><div className="section-head"><div><h2>3D specimen atlas</h2><p>Real micrograph textures · illustrative arrangement</p></div><span className="badge amber">No geological interpolation</span></div><Suspense fallback={<p className="empty-inline">Loading 3D viewer…</p>}><Spatial samples={samples} selected={selected} onSelect={id=>{if(!busy)setSelected(id)}}/></Suspense><div className="spatial-explanation"><div><h3>Keep imagery connected to its specimen</h3><p>Rotate the atlas and select a section. These planes are arranged for inspection, not at surveyed positions. They do not reconstruct an orebody or predict adjacent minerals.</p></div><button className="button primary" onClick={()=>navigate('Workspace')}>Inspect {title(selected)} <ArrowRight size={16}/></button></div><div className="spatial-requirements"><MapPin/><p><strong>To create the geographic model:</strong> attach validated coordinates, drillhole collars, depth intervals and survey paths. The sample-record form already accepts location notes; a 2D mineral mask alone cannot establish 3D geology.</p></div></section>}
 {page==='Reports'&&<><section className="panel report-overview"><div><span className="badge green"><FileText size={13}/>Recorded evaluation</span><h2>Mineral phase identification</h2><p>Checkpoint-specific accuracy on the LumenStone S2 test set. This is a recorded evaluation, not a new test run.</p><dl className="report-meta"><dt>Active model SHA-256</dt><dd>{report?.model_sha||'Unavailable'}</dd><dt>Evidence source</dt><dd>{report?.report_source||'Unavailable'}</dd><dt>Dataset split</dt><dd>12 publisher-held-out S2 sections</dd></dl></div><div className="report-actions"><button className="button primary" disabled={!report} onClick={()=>download(report,'reefprint-accuracy-evidence.json')}><Download size={16}/>Export evidence JSON</button><a className="button" href={report?.download_url||'/api/report/download'}><FileText size={16}/>Source report</a><button className="button" onClick={()=>window.print()}>Print / save PDF</button></div></section>{evidence}<section className="panel report-details"><h2>Per-phase evidence</h2><div className="table-scroll"><table><thead><tr><th>Phase</th><th>Intersection over Union</th><th>Interpretation</th></tr></thead><tbody>{metrics?.classes.map(c=><tr key={c.name}><td><span className="phase-label"><i style={{background:palette[c.name]||c.color}}/>{title(c.name)}</span></td><td>{c.iou.toFixed(4)}</td><td>{c.iou===0?'Not detected by this model':c.name==='background'?'Background class; not a mineral':'Measured on the reported test set'}</td></tr>)}</tbody></table></div><h3>Read the limitations with the scores</h3><ul>{(report?.limitations||[]).map((l,i)=><li key={i}>{l}</li>)}</ul><p className="report-disclosure">A new image prediction does not have a measured accuracy until an independent expert annotation is available. Confidence is not accuracy. This interface does not claim recovery gains or operational validation.</p></section>{workflow}</>}
 <footer className="app-footer"><span>REEFPRINT / KHANYA</span><span>Image → phases → evidence → decision</span><span>Local research prototype · No live plant connection</span></footer></main></>
}


