import {useEffect,useRef,useState} from 'react';
import {Download, Info, Loader2, ScanSearch} from 'lucide-react';
import {api,authenticatedMedia} from './client';
import {sourcePixel,grainId} from './grainPixels.mjs';
import {formatPayloadPercent,grainLiberationState,liberationExplanation} from './grainSelection.js';

type Grain={id:number;area_px:number;ecd_px:number;phases:Record<string,number>;payload_fraction:number;liberated:boolean;bbox:number[]};
type Evidence={n_grains:number;n_payload_grains:number;grains:Grain[];microns_per_pixel:number|null;association:Record<string,Record<string,number>>;liberation_by_size:{from_px:number;to_px:number|null;payload_grains:number;liberated_share:number|null}[]};
type Result={result_id:string|null;id:string;raw_url:string;mask_url:string|null;model_sha:string;scope?:string};
type Props={result:Result;palette:Record<string,string>;onDownload:(data:unknown,name:string)=>void};
const title=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
async function loadImage(src:string){const url=await authenticatedMedia(src);try{const image=new Image();image.src=url;await image.decode();return image}finally{URL.revokeObjectURL(url)}}
export default function GrainExplorer({result,palette,onDownload}:Props){
 const [evidence,setEvidence]=useState<Evidence|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[selected,setSelected]=useState<number|null>(null),[phase,setPhase]=useState('all'),[page,setPage]=useState(0),[showMask,setShowMask]=useState(true);
 const canvas=useRef<HTMLCanvasElement>(null),images=useRef<{raw:HTMLImageElement;mask:HTMLImageElement|null;ids:ImageData}|null>(null);
 useEffect(()=>{let cancelled=false;setEvidence(null);setError('');setReady(false);setSelected(null);setPhase('all');setPage(0);images.current=null;
  if(!result.result_id)return;
  Promise.all([api<Evidence>('/results/'+encodeURIComponent(result.result_id)+'/grains'),loadImage('/api/results/'+encodeURIComponent(result.result_id)+'/grain-ids.png'),loadImage(result.raw_url),result.mask_url?loadImage(result.mask_url):Promise.resolve(null)]).then(([report,ids,raw,mask])=>{
   if(cancelled)return;
   const offscreen=document.createElement('canvas');offscreen.width=ids.naturalWidth;offscreen.height=ids.naturalHeight;const ctx=offscreen.getContext('2d',{willReadFrequently:true});if(!ctx)throw Error('Your browser cannot read grain-map pixels.');ctx.drawImage(ids,0,0);
   images.current={raw,mask,ids:ctx.getImageData(0,0,offscreen.width,offscreen.height)};setEvidence(report);setReady(true);
  }).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true};
 },[result.result_id,result.raw_url,result.mask_url]);
 useEffect(()=>{const target=canvas.current,data=images.current;if(!target||!data||!ready)return;const ctx=target.getContext('2d');if(!ctx)return;target.width=data.ids.width;target.height=data.ids.height;ctx.drawImage(data.raw,0,0,target.width,target.height);if(showMask&&data.mask){ctx.globalAlpha=.5;ctx.drawImage(data.mask,0,0,target.width,target.height);ctx.globalAlpha=1}
  if(selected!=null){const highlight=ctx.createImageData(target.width,target.height);for(let offset=0;offset<data.ids.data.length;offset+=4){if(grainId(data.ids.data,offset)===selected){highlight.data[offset]=255;highlight.data[offset+1]=255;highlight.data[offset+2]=255;highlight.data[offset+3]=145}}
   const overlay=document.createElement('canvas');overlay.width=target.width;overlay.height=target.height;overlay.getContext('2d')?.putImageData(highlight,0,0);ctx.drawImage(overlay,0,0)}
 },[selected,ready,showMask]);
 const grain=evidence?.grains.find(g=>g.id===selected),filtered=(evidence?.grains||[]).filter(g=>phase==='all'||(g.phases[phase]||0)>0),rows=filtered.slice(page*20,(page+1)*20);
 function pick(clientX:number,clientY:number){if(!canvas.current||!images.current)return;const ids=images.current.ids,point=sourcePixel(clientX,clientY,canvas.current.getBoundingClientRect(),ids.width,ids.height);if(!point)return;const id=grainId(ids.data,(point[1]*ids.width+point[0])*4);setSelected(id||null)}
 return <section className="panel grain-explorer"><div className="section-head"><div className="heading-icon"><ScanSearch/><div><h2>Explore individual grains</h2><p>Grains computed from this exact predicted phase map</p></div></div><button className="button" disabled={!evidence} onClick={()=>onDownload({...result,sample_id:result.id,evidence,disclosure:'Predicted 2D image evidence. Size is in pixels unless calibration is supplied. Not an assay or validated plant response.'},result.id+'-grain-evidence.json')}><Download size={15}/>Export grain evidence</button></div>
  {error?<div className="grain-unavailable" role="status"><Info size={18}/><div><h3>Grain evidence unavailable</h3><p>{error} Run a new analysis to create evidence for this checkpoint.</p></div></div>:!ready?<p className="empty-inline" role="status"><Loader2 className="spin" size={15}/> Loading grain evidence…</p>:<>
   <div className="grain-summary"><span><strong>{evidence?.n_grains}</strong> segmented grains</span><span><strong>{evidence?.n_payload_grains}</strong> with payload phases</span><span>{evidence?.microns_per_pixel!=null?evidence.microns_per_pixel+' µm / pixel':'Pixel size uncalibrated'}</span></div>
   <div className="grain-grid"><div className="grain-view"><div className="grain-view-tools"><span>Select a grain in the image or table</span><label><input type="checkbox" checked={showMask} onChange={e=>setShowMask(e.target.checked)}/> Phase overlay</label></div><canvas ref={canvas} style={{maxWidth:images.current?520*images.current.ids.width/images.current.ids.height+'px':undefined,margin:'0 auto'}} role="img" aria-label="Predicted grain map. Use the adjacent grain table for keyboard selection." onClick={e=>pick(e.clientX,e.clientY)}/><p className="grain-caption">Highlighted pixels identify grain {selected??'—'}. Sizes and associations describe this analysed image, including its sampled field coverage.</p></div>
   <aside className="grain-inspector" aria-live="polite">{grain?<><h3>Grain {grain.id}</h3><dl><dt>Area</dt><dd>{grain.area_px.toLocaleString()} px²</dd><dt>Equivalent diameter</dt><dd>{grain.ecd_px.toFixed(1)} px</dd><dt>Valuable-mineral share</dt><dd>{formatPayloadPercent(grain.payload_fraction)}%</dd><dt>Mineral liberation state</dt><dd><span className={`grain-state grain-state--${grainLiberationState(grain.payload_fraction)==='FREE'?'free':grainLiberationState(grain.payload_fraction)==='LOCKED'?'locked':'none'}`}>{grainLiberationState(grain.payload_fraction)}</span></dd></dl><p className="grain-state-explanation">{liberationExplanation(grain.payload_fraction)}</p><h3>Within-grain composition</h3>{Object.entries(grain.phases).map(([name,share])=><div className="grain-phase" key={name}><span><i style={{background:palette[name]}}/>{title(name)}</span><strong>{(share*100).toFixed(1)}%</strong></div>)}<p>Composition uses classified mineral pixels in this grain. Liberation is a model-derived 2D flag.</p></>:<><h3>{selected===null?'Choose a grain':'Grain not listed'}</h3><p>Click a mineral grain or select a table row to inspect its size and composition. Background pixels clear the selection.</p></>}</aside></div>
   <div className="grain-table-head"><h3>Grain catalogue</h3><label>Contains phase <select value={phase} onChange={e=>{setPhase(e.target.value);setPage(0)}}><option value="all">All phases</option>{Object.keys(palette).filter(n=>n!=='background').map(n=><option key={n} value={n}>{title(n)}</option>)}</select></label></div><div className="table-scroll grain-table-scroll"><table className="grain-table"><thead><tr><th>Grain</th><th>Area (px²)</th><th>Diameter (px)</th><th>Payload fraction</th><th>Mineral state</th></tr></thead><tbody>{rows.map(g=><tr key={g.id} className={selected===g.id?'selected':''}><td><button className="text-button" aria-pressed={selected===g.id} onClick={()=>setSelected(g.id)}>Grain {g.id}</button></td><td>{g.area_px.toLocaleString()}</td><td>{g.ecd_px.toFixed(1)}</td><td>{formatPayloadPercent(g.payload_fraction)}%</td><td>{grainLiberationState(g.payload_fraction)}</td></tr>)}</tbody></table></div>{!filtered.length&&<p className="empty-inline">No grains contain this phase in the selected result.</p>}<div className="grain-pagination"><span>{filtered.length?`${page*20+1}–${Math.min((page+1)*20,filtered.length)} of ${filtered.length} grains`:'0 grains'}</span><button className="button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button" disabled={(page+1)*20>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>
   <details className="grain-detail"><summary>Boundary association and liberation by size</summary><p>Boundary contact is measured on the predicted map. Resin indicates contact with background. Liberation is payload-area weighted within pixel-diameter bins.</p><div className="grain-evidence-tables"><div className="table-scroll"><table><thead><tr><th>Phase</th><th>Neighbour</th><th>Boundary share</th></tr></thead><tbody>{Object.entries(evidence?.association||{}).flatMap(([name,neighbours])=>Object.entries(neighbours).map(([neighbour,share])=><tr key={name+neighbour}><td>{title(name)}</td><td>{title(neighbour)}</td><td>{share.toFixed(1)}%</td></tr>))}</tbody></table></div><div className="table-scroll"><table><thead><tr><th>Diameter (px)</th><th>Payload grains</th><th>Liberated share</th></tr></thead><tbody>{evidence?.liberation_by_size.map(bin=><tr key={bin.from_px}><td>{bin.from_px}–{bin.to_px??'∞'}</td><td>{bin.payload_grains}</td><td>{bin.liberated_share==null?'No payload':(bin.liberated_share*100).toFixed(1)+'%'}</td></tr>)}</tbody></table></div></div></details>
  </>}
 </section>
}
