import {useEffect,useState} from 'react';
import {ArrowRight,AlertCircle,CheckCircle2,Cpu,RefreshCw,ShieldCheck} from 'lucide-react';
import {api} from './client';
import {ThemePicker} from './theme';
type Health={model_sha?:string;model_approved?:boolean;approved_model_sha?:string;checkpoint_available?:boolean;model_ready?:boolean;cloud_sync?:boolean;deployment?:string}|null;
type ProviderStatus={local_available:boolean;provider_ready:boolean;provider:string|null;model:string|null;context_policy:string};
export default function Settings({health,onNavigate}:{health:Health;onNavigate:(page:string)=>void}){
 const [provider,setProvider]=useState<ProviderStatus|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);setError('');api<ProviderStatus>('/assistant/status').then(value=>{if(typeof value?.local_available!=='boolean'||typeof value.provider_ready!=='boolean')throw Error('The service did not return assistant status.');if(alive)setProvider(value)}).catch(reason=>{if(alive){setProvider(null);setError(reason.message)}}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[refresh]);
 return <div className="settings-layout"><section className="panel settings-appearance"><div className="section-head"><div><h2>Choose your working environment</h2><p>Appearance changes the interface; phase colours and scientific evidence stay fixed.</p></div></div><div className="settings-body"><ThemePicker/><p className="settings-help">Preferences stay on this browser, separately for each signed-in account. White workbench remains the default. Your choice does not change the model, sample data or reported accuracy.</p></div></section>
 <section className="panel settings-service"><div className="section-head"><div className="heading-icon"><Cpu size={20}/><div><h2>The model actually analysing your image</h2><p>Live service identity, separate from training experiments</p></div></div></div><div className="settings-body"><dl className="settings-facts"><dt>Segmentation architecture</dt><dd>DeepLabV3 / ResNet-50</dd><dt>Execution</dt><dd>Local CPU on the analysis server</dd><dt>Checkpoint</dt><dd>{!health?'Service status unavailable':!health.checkpoint_available?'Checkpoint unavailable':health.model_ready===false?'Loaded; warming up':'Available to the analysis service'}</dd><dt>Active SHA-256</dt><dd className="settings-sha">{health?.model_sha||'Unavailable'}</dd><dt>Approval for simulator use</dt><dd>{!health?'Unknown':health.model_approved?'Approved checkpoint':'Not approved; simulator gates remain in effect'}</dd><dt>Record storage</dt><dd>{health?.cloud_sync?'Private Supabase account records':health?'Local analysis backend':'Unknown'}</dd></dl><p className="settings-help">Kaggle trains and evaluates candidates. It is not the always-on inference service. Accuracy reports are bound to individual checkpoint hashes; a newer candidate report does not replace the active model.</p><button className="text-button" onClick={()=>onNavigate('Reports')}>Inspect checkpoint accuracy <ArrowRight size={15}/></button></div></section>
 <section className="panel settings-assistant"><div className="section-head"><div><h2>Research companion connection</h2><p>Read-only status; keys never belong in this interface</p></div><button className="button" disabled={loading} onClick={()=>setRefresh(value=>value+1)}><RefreshCw size={15}/>{loading?'Checking connection...':'Refresh assistant status'}</button></div><div className="settings-body">{loading?<p role="status">Reading the current server configuration...</p>:error?<p className="settings-error" role="alert"><AlertCircle size={17}/>{error}</p>:<><div className="settings-provider-status"><CheckCircle2 size={19}/><div><strong>{provider?.provider_ready?'Language model configured; connection not tested':'Local evidence helper available'}</strong><p>{provider?.provider_ready?`${provider.provider} / ${provider.model}`:'No external language model is configured. The evidence helper works without an API key.'}</p></div></div><p className="settings-help">A language model explains supplied evidence. DeepLabV3 identifies mineral phases. Provider access requires explicit opt-in for each conversation; configuration alone does not prove an API call works.</p><p className="settings-help">{provider?.context_policy}</p></>}
 <details className="settings-provider-help"><summary>Connect your own language model privately</summary><p>On the server, add one provider at a time to the ignored <code>.workbench/cloud.env</code> file, then restart the backend. Set <code>REEFPRINT_ASSISTANT_PROVIDER</code>, <code>REEFPRINT_ASSISTANT_MODEL</code> and, for a hosted provider, <code>REEFPRINT_ASSISTANT_API_KEY</code>.</p><p>Supported adapters: <strong>aimlapi</strong>, <strong>featherless</strong>, <strong>huggingface</strong> or local <strong>ollama</strong>. The model name must be supported by that provider. A hosted account may require its own quota or credit.</p><p>Keep the API key out of chat, screenshots, Git, sample notes and browser storage. This page displays configuration status only. No image, audio, saved note or coordinate is sent to the language model by this adapter.</p></details></div></section>
 <section className="panel settings-inputs"><div className="section-head"><div className="heading-icon"><ShieldCheck size={20}/><div><h2>Use an image the model understands</h2><p>File support is different from scientific validation</p></div></div></div><div className="settings-body"><p>Use a prepared reflected-light microscopy image resembling LumenStone S2. Upload PNG, JPEG or TIFF, up to 25 MB, at least 512 pixels on each side and no more than 30 million pixels. Colour checks can reject unsuitable images.</p><p>A phone photograph of an ore sample may pass file checks and produce a prediction, but the model has not been validated for that acquisition. Do not present its phase labels as confirmed mineralogy, grade or recovery.</p><p>Keep field photos and voice observations as sample context. Use microscopy for this trained model's demonstration; new acquisition types require expert labels and separate evaluation.</p><button className="text-button" onClick={()=>onNavigate('Workspace')}>Return to microscopy analysis <ArrowRight size={15}/></button></div></section>
 </div>;
}
