import{useEffect,useRef,useState}from'react';import*as THREE from'three';import{OrbitControls}from'three/examples/jsm/controls/OrbitControls.js';import{RotateCcw,MousePointer2}from'lucide-react';
export default function Spatial({samples,selected,onSelect}:{samples:{id:string;thumbnail_url:string}[];selected:string;onSelect:(id:string)=>void}){
const host=useRef<HTMLDivElement>(null),reset=useRef<()=>void>(()=>{}),[error,setError]=useState('');
useEffect(()=>{if(!host.current||!samples.length)return;const el=host.current;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{setError('WebGL is unavailable. Use the sample library to inspect these images.');return}
const scene=new THREE.Scene();scene.background=new THREE.Color('#edf2f6');const camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(8,7,11);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,1,0);controls.minDistance=5;controls.maxDistance=22;renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x8090a0,2));const grid=new THREE.GridHelper(16,16,0xb4c5d4,0xd8e1e9);grid.position.y=-.9;scene.add(grid);
const meshes:THREE.Mesh[]=[];const loader=new THREE.TextureLoader();samples.slice(0,12).forEach((s,i)=>{const texture=loader.load(s.thumbnail_url);texture.colorSpace=THREE.SRGBColorSpace;const geo=new THREE.PlaneGeometry(3.3,2.45);const mat=new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geo,mat);mesh.rotation.x=-Math.PI/2;mesh.position.set((i%3-1)*3.65,Math.floor(i/3)*.65,Math.floor(i/3)*2.1-3);mesh.userData.id=s.id;scene.add(mesh);meshes.push(mesh);if(s.id===selected){const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:0x2463dd}));edges.position.z=.02;mesh.add(edges)}});
const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(el);resize();let frame=0;const draw=()=>{frame=requestAnimationFrame(draw);controls.update();renderer.render(scene,camera)};draw();reset.current=()=>{camera.position.set(8,7,11);controls.target.set(0,1,0);controls.update()};const ray=new THREE.Raycaster();let downX=0,downY=0;const down=(e:PointerEvent)=>{downX=e.clientX;downY=e.clientY};const pick=(e:PointerEvent)=>{if(Math.abs(e.clientX-downX)+Math.abs(e.clientY-downY)>6)return;const r=el.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(meshes)[0];if(hit)onSelect(hit.object.userData.id)};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',pick);return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();renderer.dispose();scene.traverse(obj=>{const m=obj as THREE.Mesh;if(m.geometry)m.geometry.dispose();if(m.material){const mats=Array.isArray(m.material)?m.material:[m.material];mats.forEach(mat=>{(mat as THREE.MeshBasicMaterial).map?.dispose();mat.dispose()})}});renderer.domElement.remove()};
},[samples,selected]);
return <div className="spatial-wrap"><div className="spatial-canvas" ref={host} role="img" aria-label="Interactive 3D atlas of real specimen images arranged at illustrative positions"/><div className="spatial-overlay"><span><MousePointer2 size={15}/>Drag to orbit · scroll to zoom · click to select</span><button className="button" onClick={()=>reset.current()}><RotateCcw size={15}/>Reset view</button></div>{error&&<p role="alert">{error}</p>}<div className="spatial-selector" aria-label="Select 3D specimen">{samples.map(s=><button key={s.id} className={'button '+(s.id===selected?'primary':'')} onClick={()=>onSelect(s.id)}>{s.id.replace('_',' ')}</button>)}</div></div>
}
