import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';

test('grain selections show all three liberation states and preserve result provenance',async({page})=>{
 const externalRequests:string[]=[];
 const localOrigin=new URL(test.info().project.use.baseURL as string).origin;
 page.on('request',request=>{const url=new URL(request.url());if(['http:','https:'].includes(url.protocol)&&url.origin!==localOrigin)externalRequests.push(request.url())});
 const png=await readFile(new URL('./fixtures/grain-states.png',import.meta.url));
 await page.route('**/api/**',async route=>{
  const path=new URL(route.request().url()).pathname;
  if(path.endsWith('.png'))return route.fulfill({contentType:'image/png',body:png});
  let body:unknown={};
  if(path==='/api/config')body={auth_required:false,cloud_sync:false};
  if(path==='/api/samples')body=[{id:'test_11',thumbnail_url:'/api/raw.png',dimensions:[3,1],dataset:'Test fixture',has_prediction:true}];
  if(path==='/api/health')body={status:'ok',checkpoint_available:false};
  if(path==='/api/report')body={model_sha:'fixture-sha',checkpoint_matches_report:false,metrics:null,limitations:[]};
  if(path==='/api/samples/test_11/record')body={version:0,record:{}};
  if(path==='/api/samples/test_11')body={id:'test_11',result_id:'fixture-result',raw_url:'/api/raw.png',mask_url:'/api/mask.png',phases:[],model_sha:'fixture-sha',scope:'Two-pixel test fixture',prediction_source:'cached',advisory:{action:'Hold',reason:'Test fixture'},confidence:.5};
  if(path==='/api/results/fixture-result/grains')body={n_grains:3,n_payload_grains:2,microns_per_pixel:null,association:{},liberation_by_size:[],grains:[{id:1,area_px:1,ecd_px:1.1,phases:{chalcopyrite:1},payload_fraction:.5,liberated:true,bbox:[0,0,0,0]},{id:2,area_px:1,ecd_px:1.1,phases:{pyrrhotite:1},payload_fraction:0,liberated:false,bbox:[1,0,1,0]},{id:3,area_px:1,ecd_px:1.1,phases:{pentlandite:.0004,pyrrhotite:.9996},payload_fraction:.0004,liberated:false,bbox:[2,0,2,0]}]};
  return route.fulfill({json:body});
 });
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Explore individual grains'})).toBeVisible();
 const image=page.getByRole('img',{name:/Predicted grain map/});
 const rect=await image.boundingBox();if(!rect)throw Error('Grain canvas missing');
 await image.click({position:{x:rect.width*.17,y:rect.height*.5}});
 await expect(page.locator('.grain-inspector').getByRole('heading',{name:'Grain 1',exact:true})).toBeVisible();
 await expect(page.locator('.grain-inspector').getByText('FREE',{exact:true})).toBeVisible();
 await image.click({position:{x:rect.width*.5,y:rect.height*.5}});
 await expect(page.locator('.grain-inspector').getByRole('heading',{name:'Grain 2',exact:true})).toBeVisible();
 await expect(page.locator('.grain-inspector').getByText('NO VALUABLE MINERALS',{exact:true})).toBeVisible();
 await expect(page.locator('.grain-inspector').getByText(/No valuable mineral is present/)).toBeVisible();
 await image.click({position:{x:rect.width*.83,y:rect.height*.5}});
 await expect(page.locator('.grain-inspector').getByRole('heading',{name:'Grain 3',exact:true})).toBeVisible();
 await expect(page.locator('.grain-inspector').getByText('LOCKED',{exact:true})).toBeVisible();
 await expect(page.locator('.grain-inspector').getByText('0.04%',{exact:true})).toBeVisible();
 await expect(page.locator('.grain-inspector').getByText(/below the 50% free-particle threshold/)).toBeVisible();
 const grainOne=page.getByRole('button',{name:'Grain 1',exact:true});await grainOne.focus();await page.keyboard.press('Enter');
 await expect(page.locator('.grain-inspector').getByRole('heading',{name:'Grain 1',exact:true})).toBeVisible();
 await page.getByLabel('Contains phase').selectOption('pyrrhotite');
 await expect(page.getByRole('button',{name:'Grain 1',exact:true})).toHaveCount(0);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export grain evidence'}).click();const download=await downloadPromise;
 expect(download.suggestedFilename()).toBe('test_11-grain-evidence.json');
 const downloadedPath=await download.path();if(!downloadedPath)throw Error('Evidence download missing');
 const exported=JSON.parse(await readFile(downloadedPath,'utf8'));
 expect(exported.result_id).toBe('fixture-result');expect(exported.model_sha).toBe('fixture-sha');expect(exported.evidence.n_grains).toBe(3);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
 await page.screenshot({path:test.info().outputPath('grain-explorer-mobile.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:1000});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
 await page.screenshot({path:test.info().outputPath('grain-explorer-desktop.png'),fullPage:true});
 expect(externalRequests,'local grain inspection must stay offline when cloud authentication is disabled').toEqual([]);
});
